<a href="https://colab.research.google.com/github/mykola-mmm/myCollabs/blob/main/UpSampling_vs_Conv2DTranspose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import asarray
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import UpSampling2D, Input


In [ ]:
X = asarray([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
X.shape

(3, 3)

In [ ]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
X = X.reshape(1, X.shape[0], X.shape[1], 1)

In [ ]:
X.shape

(1, 3, 3, 1)

In [ ]:
X

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]])

In [ ]:
model = Sequential()
model.add(Input(shape=(X.shape[1], X.shape[2],1)))
model.add(UpSampling2D(size=(3,2)))
model.summary()

Model: "sequential_43"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 up_sampling2d_19 (UpSampli  (None, 9, 6, 1)           0         
 ng2D)                                                           
                                                                 
Total params: 0 (0.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
upsampled_X = model.predict(X)

1/1 [==============================] - 0s 54ms/step


In [ ]:
upsampled_X = upsampled_X.reshape((upsampled_X.shape[1],upsampled_X.shape[2]))

In [ ]:
upsampled_X

array([[1., 1., 2., 2., 3., 3.],
       [1., 1., 2., 2., 3., 3.],
       [1., 1., 2., 2., 3., 3.],
       [4., 4., 5., 5., 6., 6.],
       [4., 4., 5., 5., 6., 6.],
       [4., 4., 5., 5., 6., 6.],
       [7., 7., 8., 8., 9., 9.],
       [7., 7., 8., 8., 9., 9.],
       [7., 7., 8., 8., 9., 9.]], dtype=float32)

In [ ]:
from numpy import asarray
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2DTranspose, Input


In [ ]:
Y = asarray([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
Y.shape

(3, 3)

In [ ]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Y = Y.reshape(1, Y.shape[0], Y.shape[1], 1)

In [ ]:
Y.shape

(1, 3, 3, 1)

In [ ]:
Y

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]])

In [ ]:
# model_Y = Sequential()
# model_Y.add(Input(shape=(Y.shape[1], Y.shape[2],1)))
# model_Y.add(Conv2DTranspose(1, (1,1), strides = (2,2), kernel_initializer = 'ones'  ))
# model_Y.summary()

model_Y = Sequential()
model_Y.add(Input(shape=(Y.shape[1], Y.shape[2],1)))
model_Y.add(Conv2DTranspose(1, (1,1), strides = (2,2), kernel_initializer = 'ones'))
model_Y.summary()

upsampled_Y = model_Y.predict(Y)
print(upsampled_Y.shape)

Model: "sequential_45"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose_23 (Conv2  (None, 6, 6, 1)           2         
 DTranspose)                                                     
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
1/1 [==============================] - 0s 89ms/step
(1, 6, 6, 1)


In [ ]:
upsampled_Y = model_Y.predict(Y)

1/1 [==============================] - 0s 35ms/step


In [ ]:
upsampled_Y = upsampled_Y.reshape((upsampled_Y.shape[1], upsampled_Y.shape[2]))

In [ ]:
upsampled_Y

array([[1., 1., 2., 2., 3., 3.],
       [1., 1., 2., 2., 3., 3.],
       [4., 4., 5., 5., 6., 6.],
       [4., 4., 5., 5., 6., 6.],
       [7., 7., 8., 8., 9., 9.],
       [7., 7., 8., 8., 9., 9.]], dtype=float32)